document.addEventListener('DOMContentLoaded', function() {
    // List of fun facts
    var funFacts = [
      "Help",
      "HEY!",
      "I walk to Burger King, and then I walk back home from burger king 🔥😔",
      "SCOTLAND FOREVER!",
      "Someone is always watching",
      "I'm just gonna say it, Thundercat is amazing!",
      "L",
      "W",
      "It's a beautiful day outside. Birds are singing, flowers are blooming.",
      "This is one of the many random messages that can appear when you load the page.",
      "Hopes and dreams",
      "Classic",
      "Deltarune",
      "Here is my favorite game of all time:",
      "Have you ever seen a cat?",
      "Lucky Charm is the greatest dog ever!",
      "Where am I going?",
      "Thunderstruck",
      "Them Changes",
      "A Fan's Mail",
      "Minecraft",
      "Minceraft",
      "Turip ip ip ip",
      "wenomechainsama",
      "dogs are cool",
      "Cats, are cool. Cool to be a cat.",
      "Wonk",
      "Yoink",
      "Rizz",
      "real",
      "Dr. Pepper",
      "Lemons",
      "Hamburger",
      "Cheeseburger",
      "SANS!!!",
      "youtube.com",
      "j",
      "ello",
      "hi",
      "this message will never be seen!",
      "welcome",
      "welmone",
      "minecraft sign",
      "update",
      "call yourself",
      "what the h*ck",
      "omg",
      "what in the actual t*rnation?!",
      "Capital",
      "https://youtube.com",
      "My teeth are disintegrating",
      "Spongebob Squarepants",
      "Spongebob patrick squidward sandy",
      "web",
      "no swearing",
      "who am i",
      "REFRESH THE PAGE!! HURRY, BEFORE ITS TOO LATE!!",
      "Toby Fox",
      "",
      ".",
      "3",
      "9",
      "7",
      "Are you real?",
      "Click here",
      "Control + W to close this tab",
      "cat",
      "dog",
      "If you see this message, it means you have blue eyes.",
      "If you see this message, your name starts with an A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y or Z.",
      "I never gave you permission to come here",
      "Money",
      "ahjsdfghabuij,;kj;awbjk;sdlfjkjaksdnjfsdfasjkldfjasjkldfnanlskdfjajlk",
      "Ah-rah, dee Soo-guh-goo-gee-goo-gee Goo-guh fli-goo gee-goo Guh fli-goo, ga-goo-buh-dee Ooh, guh-goo-bee Ooh-guh-guh-bee-guh-guh-bee Fli-goo gee-goo A-fliguh woo-wa mama Lucifer!"
    ];
  
    // Get a random index from the funFacts array
    var randomIndex = Math.floor(Math.random() * funFacts.length);
  
    // Get the paragraph element to display the fun fact
    var funFactElement = document.getElementById('fun-fact');
  
    // Display the random fun fact
    funFactElement.textContent = funFacts[randomIndex];
  });
  